>>> def binary_search(ar, target):
...     
...     left=0
...     right=len(ar) - 1
...     
...     while left <= right:
...         mid = left + (right - left) // 2
...         
...         if ar[mid] == target:
...             return mid
...         
...         elif ar[mid] < target:
...             left = mid + 1
...             
...         else:
...             right = mid - 1
...     
...     return -1
... 
... 
... ar = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
... target = 3
... 
... result = binary_search(ar, target)
... if result != -1:
...     print("Element found at index",str(ar))
... else:
...     print("Element not found in the array")
